// swift-tools-version: 5.7

// This file was automatically generated by PackageGenerator and untracked
// PLEASE DO NOT EDIT MANUALLY

import PackageDescription

let package = Package(
    name: "Example",
    defaultLocalization: "en",
    platforms: [.iOS(.v14)],
    products: [
        .library(
            name: "Example",
            targets: ["Example"]
        )
    ],
    dependencies: [
        .package(
            path: "../MyLocalFramework"
        ),
        .package(
            url: "https://github.com/Alamofire/Alamofire",
            exact: "5.6.1"
        ),
        .package(
            url: "https://github.com/nalexn/ViewInspector",
            exact: "0.9.2"
        ),
    ],
    targets: [
        .target(
            name: "Example",
            dependencies: [
                .product(name: "Alamofire", package: "Alamofire"),
                .target(name: "GoogleMaps"),
            ],
            path: "Framework/Sources",
            resources: [
                .process("Resources")
            ],
            plugins: []
        ),
        .testTarget(
            name: "UnitTests",
            dependencies: [
                .byName(name: "Example"),
                .product(name: "ViewInspector", package: "ViewInspector"),
            ],
            path: "Tests/Sources",
            resources: [
                .process("Resources")
            ],
            plugins: []
        ),
        .binaryTarget(
            name: "GoogleMaps",
            path: "../../vendor/GoogleMaps-7.1.0/GoogleMaps.xcframework"
        ),
    ]
)
