// swift-tools-version: 6.0

// This file was automatically generated by PackageGenerator and is untracked
// PLEASE DO NOT EDIT MANUALLY

import PackageDescription

let package = Package(
    name: "Registry",
    defaultLocalization: "en",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "Registry",
            targets: ["TargetA"]
        ),
    ],
    dependencies: [
        .package(
            path: "../LocalDependencies"
        ),
        .package(
            url: "https://github.com/RemoteDependencyE",
            exact: "3.0.0"
        ),
    ],
    targets: [
        .target(
            name: "TargetA",
            dependencies: [
                .product(name: "LocalDependencyA", package: "LocalDependencyA"),
                .product(name: "RemoteDependencyE_SDK", package: "RemoteDependencyE_SDK"),
            ],
            path: "Framework/Sources",
            resources: [
                .process("Resources")
            ],
            plugins: [
            ]
        ),
        .testTarget(
            name: "TargetATests",
            dependencies: [
                .byName(name: "TargetA"),
                .product(name: "RemoteDependencyE_SDK", package: "RemoteDependencyE_SDK"),
            ],
            path: "Tests/Sources",
            resources: [
                .process("Resources")
            ],
            plugins: [
            ]
        ),
    ]
)