// swift-tools-version: 5.9

// This file was automatically generated by PackageGenerator and is untracked
// PLEASE DO NOT EDIT MANUALLY

import PackageDescription

#if TUIST
    import struct ProjectDescription.PackageSettings

    let packageSettings = PackageSettings(
        productTypes: [
            "ModA": .staticFramework,
            "ModB": .staticFramework,
            "ModC": .staticFramework,
            "RemoteDependencyA": .staticFramework,
            "RemoteDependencyB": .staticFramework,
            "RemoteDependencyC": .staticFramework,
            "RemoteDependencyD": .staticFramework
        ]
    )
#endif

let package = Package(
    name: "JustEatTakeaway",
    dependencies: [
        .package(path: "../Modules/ModA"),
        .package(path: "../Modules/ModB"),
        .package(path: "../Modules/ModC"),
        .package(url: "https://github.com/RemoteDependencyA", exact: "1.0.0"),
        .package(url: "https://github.com/RemoteDependencyB", exact: "2.0.0"),
        .package(url: "https://github.com/RemoteDependencyC", revision: "abcde1235kjh"),
        .package(url: "https://github.com/RemoteDependencyD", branch: "master")
    ]
)
